# HTML Language Code Reference
languageCode = "en-us"
DefaultContentLanguage = "en"
# Site settings
baseURL = "http://danno.co" 
title = "Dan Hanasono | Product Designer"
description = "Danno's product portfolio site"
InstagramUser = "brkfstburrito"
TwitterUser = "danhanasono"
AngelCoUser = "danhanasono"
MediumUser = "dannoh"
ProductHuntUser = "danhanasono"
Email = "dan.hanasono@gmail.com"
CopyrightHTML = "copyright.html"
# Sitemap settings
# Site settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"