languageCode = "en-us"
title = "Dan Hanasono | Product Manager"
baseURL = "http://danno.co"
description = "Danno's product portfolio site"
TwitterUser = "danhanasono"
CopyrightHTML = ""
DefaultContentLanguage = "en"